targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          generic_argument_factories: true
          field_rename: snake
      freezed|freezed:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.freezed.dart'
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'