#!/usr/bin/env bash
# Local WebDAV server for interactive Velock Sync testing.
#
# Usage:
#   tool/local_webdav/start_local_webdav.sh [start|stop|restart|status]
#
# Overridable environment variables:
#   WEBDAV_PORT (default 8888), WEBDAV_USER (velock), WEBDAV_PASSWORD (velock123),
#   WEBDAV_ROOT (default ui_test_results/persistent-webdav-root),
#   WEBDAV_VENV (default ui_test_results/webdav_venv)
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
WEBDAV_PORT="${WEBDAV_PORT:-8888}"
WEBDAV_USER="${WEBDAV_USER:-velock}"
WEBDAV_PASSWORD="${WEBDAV_PASSWORD:-velock123}"
WEBDAV_ROOT="${WEBDAV_ROOT:-$ROOT_DIR/ui_test_results/persistent-webdav-root}"
WEBDAV_VENV="${WEBDAV_VENV:-$ROOT_DIR/ui_test_results/webdav_venv}"
WEBDAV_BIN="$WEBDAV_VENV/bin/wsgidav"

RUN_DIR="$ROOT_DIR/ui_test_results/local-webdav"
CONFIG_FILE="$RUN_DIR/wsgidav.yaml"
LOG_FILE="$RUN_DIR/webdav.log"
PID_FILE="$RUN_DIR/webdav.pid"

action="${1:-start}"

is_running() {
  [[ -f "$PID_FILE" ]] || return 1
  local pid
  pid="$(cat "$PID_FILE" 2>/dev/null || true)"
  [[ -n "$pid" ]] || return 1
  kill -0 "$pid" 2>/dev/null
}

lan_ip() {
  ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo 127.0.0.1
}

write_config() {
  mkdir -p "$RUN_DIR" "$WEBDAV_ROOT"
  cat > "$CONFIG_FILE" <<YAML
# Generated by tool/local_webdav/start_local_webdav.sh -- do not edit by hand.
host: "0.0.0.0"
port: $WEBDAV_PORT
provider_mapping:
  "/": "$WEBDAV_ROOT"
http_authenticator:
  domain_controller: wsgidav.dc.simple_dc.SimpleDomainController
  accept_basic: true
  accept_digest: false
  default_to_digest: false
simple_dc:
  user_mapping:
    "*":
      $WEBDAV_USER:
        password: "$WEBDAV_PASSWORD"
dir_browser:
  enable: false
verbose: 2
YAML
}

stop_server() {
  if ! is_running; then
    echo "WebDAV is not running."
    rm -f "$PID_FILE"
    return 0
  fi
  local pid
  pid="$(cat "$PID_FILE")"
  kill -TERM "$pid" 2>/dev/null || true
  for _ in {1..40}; do
    kill -0 "$pid" 2>/dev/null || break
    sleep 0.25
  done
  kill -0 "$pid" 2>/dev/null && kill -KILL "$pid" 2>/dev/null || true
  rm -f "$PID_FILE"
  echo "Stopped WebDAV (pid $pid)."
}

start_server() {
  [[ -x "$WEBDAV_BIN" ]] || { echo "WsgiDAV not found: $WEBDAV_BIN" >&2; exit 3; }
  if is_running; then
    echo "WebDAV already running (pid $(cat "$PID_FILE"))."
  else
    if lsof -nP -iTCP:"$WEBDAV_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
      echo "Port $WEBDAV_PORT is already in use:" >&2
      lsof -nP -iTCP:"$WEBDAV_PORT" -sTCP:LISTEN >&2
      exit 6
    fi
    write_config
    nohup "$WEBDAV_BIN" --config "$CONFIG_FILE" >>"$LOG_FILE" 2>&1 &
    echo $! > "$PID_FILE"
    for _ in {1..40}; do
      curl --silent --fail --user "$WEBDAV_USER:$WEBDAV_PASSWORD" \
        --request OPTIONS --output /dev/null \
        "http://127.0.0.1:$WEBDAV_PORT/" && break
      sleep 0.25
    done
    if ! is_running; then
      echo "WsgiDAV failed to start. See $LOG_FILE" >&2
      exit 6
    fi
    echo "Started WebDAV (pid $(cat "$PID_FILE"))."
  fi
  cat <<INFO

  URL       http://127.0.0.1:$WEBDAV_PORT   (simulator / same Mac)
            http://$(lan_ip):$WEBDAV_PORT   (physical device on the same Wi-Fi)
  Username  $WEBDAV_USER
  Password  $WEBDAV_PASSWORD
  Root      $WEBDAV_ROOT
  Log       $LOG_FILE
INFO
}

case "$action" in
  start) start_server ;;
  stop) stop_server ;;
  restart) stop_server; start_server ;;
  status)
    if is_running; then
      echo "WebDAV running (pid $(cat "$PID_FILE")) on port $WEBDAV_PORT."
    else
      echo "WebDAV not running."
      exit 1
    fi
    ;;
  *) echo "Usage: $0 [start|stop|restart|status]" >&2; exit 2 ;;
esac
