#!/usr/bin/env python3
"""Checks tool/l10n/translations/<code>/*.json against sync_strings.json and
generates lib/l10n/translations/sync_translations.dart.

  python3 tool/l10n/gen_translations.py          # check + generate
  python3 tool/l10n/gen_translations.py --split  # (re)write tool/l10n/source/part*.json
"""
import json, re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
L10N = ROOT / 'tool/l10n'
CODES = ['zh-Hant', 'ar', 'de', 'es', 'fr', 'hi', 'id', 'it', 'ja', 'ko',
         'nl', 'pl', 'pt', 'ru', 'tr', 'vi']
PARTS = 4
PH = re.compile(r'\{(\d+)\}')
HAN = re.compile(r'[\u4e00-\u9fff]')

strings = json.loads((L10N / 'sync_strings.json').read_text())
keys = sorted(strings)

if '--split' in sys.argv:
    out = L10N / 'source'
    out.mkdir(exist_ok=True)
    size = -(-len(keys) // PARTS)
    for i in range(PARTS):
        chunk = {k: strings[k] for k in keys[i * size:(i + 1) * size]}
        (out / f'part{i + 1}.json').write_text(
            json.dumps(chunk, ensure_ascii=False, indent=2) + '\n')
    print(f'{len(keys)} strings in {PARTS} parts')
    sys.exit(0)

def dart(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') \
        .replace('\n', '\\n').replace('\r', '\\r') + "'"

problems, tables = [], {}
for code in CODES:
    folder = L10N / 'translations' / code
    table = {}
    for f in sorted(folder.glob('part*.json')) if folder.exists() else []:
        table.update(json.loads(f.read_text()))
    if not table:
        problems.append(f'{code}: no translations yet')
        continue
    # Keys without any letters (" ", "{0} {1}", "{0} · {1}") stay as they are.
    for k in keys:
        if not re.search(r'[^\W\d_]', PH.sub('', k)):
            table[k] = k
    missing = [k for k in keys if k not in table]
    extra = [k for k in table if k not in strings]
    if missing:
        problems.append(f'{code}: {len(missing)} missing, e.g. {missing[:3]}')
    if extra:
        problems.append(f'{code}: {len(extra)} unknown keys, e.g. {extra[:3]}')
    for k, v in table.items():
        if k not in strings:
            continue
        if v == k:
            continue
        if not isinstance(v, str) or not v.strip():
            problems.append(f'{code}: empty translation for {k!r}')
            continue
        if sorted(PH.findall(k)) != sorted(PH.findall(v)):
            problems.append(f'{code}: placeholders differ for {k!r}: {v!r}')
        if code not in ('zh-Hant', 'ja') and HAN.search(v):
            problems.append(f'{code}: Chinese characters in {k!r}: {v!r}')
    tables[code] = {k: table[k] for k in keys if k in table}

lines = ['// GENERATED by tool/l10n/gen_translations.py — do not edit by hand.',
         '// ignore_for_file: lines_longer_than_80_chars', '',
         '/// Translations keyed by the English text, per language code.',
         'const Map<String, Map<String, String>> syncTranslations = {']
for code, table in tables.items():
    lines.append(f'  {dart(code)}: {{')
    lines += [f'    {dart(k)}: {dart(v)},' for k, v in table.items()]
    lines.append('  },')
lines.append('};')
(ROOT / 'lib/l10n/translations/sync_translations.dart').write_text('\n'.join(lines) + '\n')
print(f'generated {len(tables)} languages')
for p in problems:
    print('  ' + p)
sys.exit(1 if any('missing' in p or 'placeholders' in p or 'Chinese' in p or 'empty' in p for p in problems) else 0)
